# Generated by Django 4.2 on 2023-04-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_comment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="posted_by",
            field=models.CharField(default="", max_length=100),
        ),
    ]
