# Generated by Django 4.2 on 2023-04-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_comment_posted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="posted_by",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
